#!/bin/bash

find /data/senic-hub/ -type f | xargs rm 1> /dev/null
nmcli --fields NAME,TYPE con | grep -v -w '802-3-ethernet' | awk '{if (NR!=1) {print $1}}' | while read -r line ; do nmcli con del $line; done
/sbin/reboot
